server:
  port: 8765
spring:
  application:
    name: GateWay
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: one
        uri: lb://Admin-API
        predicates:
        - Path=/admin
      - id: two
        uri: lb://User-API
        predicates:
        - Path=/user
          
          

          
          
